import * as React from "react";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function test() {
  return (
    <div className={styles.container} >
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Stack direction="row" spacing={2}>
      <Button variant="outlined">Primary</Button>
      <Button variant="outlined" disabled>
        Disabled
      </Button>
      <Button variant="outlined" href="#outlined-buttons">
        Link
      </Button>
    </Stack>
    </div>
  );
}
